document.addEventListener('DOMContentLoaded', () => {
    // --- LIVE DATA FETCHING ---
    async function fetchLiveResults() {
        try {
            // Fetch the JSON file generated by your backend/GitHub Action
            const response = await fetch('lotto-results.json');
            if (!response.ok) throw new Error('Data not found');
            
            const data = await response.json();
            
            // Update 6/58 Data
            updateCard('58', data['6/58']);
            // Update 6/55 Data
            updateCard('55', data['6/55']);
            
            document.getElementById('last-updated').textContent = `Last synchronized: ${new Date().toLocaleDateString()}`;
            
        } catch (error) {
            console.error("Error fetching live data:", error);
            document.getElementById('last-updated').textContent = "Error loading live data. Showing fallback.";
        }
    }

    function updateCard(gameId, gameData) {
        if (!gameData) return;
        
        const container = document.getElementById(`draw-${gameId}`);
        const dateElement = document.getElementById(`date-${gameId}`);
        
        container.innerHTML = ''; // Clear loader
        
        // Split combination string (e.g., "08-14-22-35-41-58") into array
        const numbers = gameData.combination.split('-');
        
        numbers.forEach(num => {
            const ball = document.createElement('span');
            ball.classList.add('ball');
            ball.textContent = num;
            container.appendChild(ball);
        });
        
        dateElement.textContent = `Draw Date: ${gameData.date}`;
    }

    // Call the fetch function when page loads
    fetchLiveResults();

    // --- GENERATOR LOGIC ---
    const generateBtn = document.getElementById('generate-btn');
    const gameSelect = document.getElementById('game-select');
    const resultContainer = document.getElementById('result-container');

    generateBtn.addEventListener('click', () => {
        const maxNumber = parseInt(gameSelect.value);
        const combination = generateCombination(maxNumber);
        
        resultContainer.innerHTML = '';
        combination.forEach(num => {
            const ball = document.createElement('span');
            ball.classList.add('ball');
            ball.textContent = num.toString().padStart(2, '0');
            resultContainer.appendChild(ball);
        });
        resultContainer.classList.remove('hidden');
    });

    function generateCombination(max) {
        const numbers = new Set();
        while (numbers.size < 6) {
            numbers.add(Math.floor(Math.random() * max) + 1);
        }
        return Array.from(numbers).sort((a, b) => a - b);
    }
});