document.addEventListener('DOMContentLoaded', () => {
    // Every PCSO game, in the order they appear on the dashboard. Games the
    // scraper hasn't filled in yet still get a card, so nothing is hidden.
    const GAME_CATALOG = [
        { id: 'ultra-lotto-6-58', name: 'Ultra Lotto 6/58' },
        { id: 'grand-lotto-6-55', name: 'Grand Lotto 6/55' },
        { id: 'super-lotto-6-49', name: 'Super Lotto 6/49' },
        { id: 'mega-lotto-6-45', name: 'Mega Lotto 6/45' },
        { id: 'lotto-6-42', name: 'Lotto 6/42' },
        { id: '6d-lotto', name: '6D Lotto' },
        { id: '4d-lotto', name: '4D Lotto' },
        { id: '3d-lotto-2pm', name: '3D Lotto 2PM' },
        { id: '3d-lotto-5pm', name: '3D Lotto 5PM' },
        { id: '3d-lotto-9pm', name: '3D Lotto 9PM' },
        { id: '2d-lotto-11am', name: '2D Lotto 11AM' },
        { id: '2d-lotto-4pm', name: '2D Lotto 4PM' },
        { id: '2d-lotto-9pm', name: '2D Lotto 9PM' }
    ];

    // --- LIVE DATA FETCHING ---
    async function fetchLiveResults() {
        const status = document.getElementById('last-updated');

        try {
            // Fetch the JSON file generated by your backend/GitHub Action
            const response = await fetch('lotto-results.json');
            if (!response.ok) throw new Error('Data not found');

            const data = await response.json();
            const games = data.games || {};

            renderResults(games);
            status.textContent = data.generated_at
                ? `Last synchronized: ${formatDate(data.generated_at.slice(0, 10))}`
                : 'Last synchronized: unknown';

        } catch (error) {
            console.error("Error fetching live data:", error);
            renderResults({});
            status.textContent = "Error loading live data.";
        }
    }

    function renderResults(games) {
        const grid = document.getElementById('results-grid');

        // Show the known games first, then anything else the scraper found
        // (a game PCSO added that isn't in the catalog yet).
        const extras = Object.keys(games)
            .filter(id => !GAME_CATALOG.some(game => game.id === id))
            .map(id => ({ id: id, name: games[id].name || id }));

        grid.innerHTML = '';
        GAME_CATALOG.concat(extras).forEach(game => {
            grid.appendChild(buildCard(game, games[game.id]));
        });
    }

    function buildCard(game, gameData) {
        const card = document.createElement('div');
        card.classList.add('card');

        const title = document.createElement('h3');
        title.textContent = game.name;
        card.appendChild(title);

        if (!gameData || !gameData.combination) {
            card.classList.add('card-pending');
            const pending = document.createElement('p');
            pending.classList.add('pending');
            pending.textContent = 'Awaiting results';
            card.appendChild(pending);
            return card;
        }

        const balls = document.createElement('div');
        balls.classList.add('balls');

        // Split combination string (e.g., "08-14-22-35-41-58") into array
        gameData.combination.split('-').forEach(num => {
            const ball = document.createElement('span');
            ball.classList.add('ball');
            ball.textContent = num;
            balls.appendChild(ball);
        });
        card.appendChild(balls);

        if (gameData.jackpot) {
            const jackpot = document.createElement('p');
            jackpot.classList.add('jackpot');
            jackpot.textContent = gameData.jackpot;
            card.appendChild(jackpot);
        }

        const meta = document.createElement('p');
        meta.classList.add('meta');
        meta.textContent = `Draw Date: ${formatDate(gameData.draw_date)}`;
        card.appendChild(meta);

        return card;
    }

    // Format "2026-08-14" as "Aug 14, 2026", building the date from its parts
    // so it doesn't shift a day in timezones behind UTC.
    function formatDate(isoDate) {
        if (!isoDate) return 'Unknown';

        const parts = isoDate.split('-').map(Number);
        const date = new Date(parts[0], parts[1] - 1, parts[2]);
        if (isNaN(date)) return isoDate;

        return date.toLocaleDateString('en-US', {
            month: 'short', day: 'numeric', year: 'numeric'
        });
    }

    // Call the fetch function when page loads
    fetchLiveResults();

    // --- GENERATOR LOGIC ---
    const generateBtn = document.getElementById('generate-btn');
    const gameSelect = document.getElementById('game-select');
    const resultContainer = document.getElementById('result-container');

    generateBtn.addEventListener('click', () => {
        const maxNumber = parseInt(gameSelect.value);
        const combination = generateCombination(maxNumber);
        
        resultContainer.innerHTML = '';
        combination.forEach(num => {
            const ball = document.createElement('span');
            ball.classList.add('ball');
            ball.textContent = num.toString().padStart(2, '0');
            resultContainer.appendChild(ball);
        });
        resultContainer.classList.remove('hidden');
    });

    function generateCombination(max) {
        const numbers = new Set();
        while (numbers.size < 6) {
            numbers.add(Math.floor(Math.random() * max) + 1);
        }
        return Array.from(numbers).sort((a, b) => a - b);
    }
});